-- =============================================================
--  Xaris & Tasos Wedding — Supabase Schema
--  Run this once in Supabase → SQL Editor
-- =============================================================

-- RSVPs table
create table if not exists public.rsvps (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),

  -- Required guest fields
  name        text not null
                check (char_length(name) between 1 and 200),
  email       text not null
                check (email ~* '^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$'),
  attendance  text not null
                check (attendance in ('yes', 'no')),
  guests      integer not null default 1
                check (guests between 1 and 10),

  -- Optional fields
  dietary     text check (char_length(coalesce(dietary, '')) <= 500),
  message     text check (char_length(coalesce(message, '')) <= 1000)
);

-- ── Row Level Security ───────────────────────────────────────
alter table public.rsvps enable row level security;

-- Anonymous guests can INSERT their own RSVP
create policy "Guests can submit RSVPs"
  on public.rsvps
  for insert
  to anon
  with check (true);

-- Nobody can SELECT all RSVPs via the public API
-- (Read-only admin access is via the Supabase dashboard or a
--  server-side function using the service_role key)

-- Authenticated users (the couple, logged in via Supabase Auth) can read all RSVPs
create policy "Authenticated admins can read RSVPs"
  on public.rsvps
  for select
  to authenticated
  using (true);

-- ── Performance indexes ──────────────────────────────────────
create index if not exists rsvps_attendance_idx  on public.rsvps (attendance);
create index if not exists rsvps_created_at_idx  on public.rsvps (created_at desc);

-- ── Helpful admin view (optional) ───────────────────────────
-- Paste into SQL Editor whenever you want an RSVP summary:
--
-- select
--   attendance,
--   count(*) as responses,
--   sum(case when attendance = 'yes' then guests else 0 end) as total_guests
-- from public.rsvps
-- group by attendance;
